### PR TITLE
If all series types match the chart type it isn't a combo chart

### LINKED ISSUE #4132: Stacked Area Charts Don't Stack
### Description
Prior to 3.44.1, stacked area charts would stack, even with a combo chart. I have a combo chart that has used stacked bars, stacked areas and a single line for over a year. But as of 3.44.1, the bars stack, but the areas do not stack. Even after removing all other series except for the areas and they still won't stack. Even Apexchart's website's demo for stacked areas doesn't stack now.

### Steps to Reproduce

1. Create a simple stacked area chart
2. Observe that chart does not stack (areas overlap instead of stacking)
3. Or review the apexcharts stacked area page (https://apexcharts.com/javascript-chart-demos/area-charts/stacked/) and observe that the areas are not stacked

### Expected Behavior
In the codepen/reproduction link, I would expect the values to stack and plot on the Y value at the sum of all values. For example, the last values in 1999 are 125 and 100, which, stacked, should plot at 225.

In the screenshot of the apex charts website, the values are 20, 11, 10, which stacked would plot at 41.

### Actual Behavior
"Stacked" areas (in codepen and apex charts website screenshot) are overlapping, not stacking.

### Screenshots
This is from the apex charts website to show even the demo is not functioning properly
apex_charts_website_stacked_area_demo

### Reproduction Link
https://codepen.io/krcoats/pen/OJdrLKW

Thank you for the help.

### PR DESCRIPTION
**Pull request by rosco54**
# New Pull Request

The default type for chart is "line" and the default for series is the chart type, therefore, if the types of all series match the chart type, this should not be considered a combo chart. Previously, if any series had a defined type, the chart was considered a combo chart.

Fixes #4132

The CodePen example in the original  bug report will stack correctly with this fix, but as far as I know it doesn't restore the behaviour the reporter claims was working in revisions prior to 3.44.1.

### Before
2fz93k98

### After

t51xbkn1 (1)

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: src/modules/CoreUtils.js [hunk 1]
```diff
@@ -8,12 +8,19 @@ class CoreUtils {
...
 
-  static checkComboSeries(series) {
+  static checkComboSeries(series, chartType) {
     let comboCharts = false
     let comboBarCount = 0
     let comboCount = 0
-
-    // if user specified a type in series too, turn on comboCharts flag
+    
+    if (chartType === 'undefined') {
```
Comment (junedchhipa) [inline src/modules/CoreUtils.js:16]: undefined as a string should be checked as `typeof chartType === 'undefined'`

File: src/modules/Core.js [hunk 2]
```diff
@@ -178,9 +178,16 @@ export default class Core {
       i: [],
     }
 
+    let chartType = cnf.chart.type !== 'undefined' ? cnf.chart.type : 'line'
```
Comment (junedchhipa) [inline src/modules/Core.js:181]: undefined as a string should be checked as `typeof cnf.chart.type !== 'undefined'`

**Review by junedchhipa — CHANGES_REQUESTED** [review]

File: src/modules/CoreUtils.js (hunk 1 above)
Comment (rosco54) [reply src/modules/CoreUtils.js]: Thanks. Done

**Review by junedchhipa — APPROVED** [review]
