### PR TITLE
Fix for incorrect representation when using logarithmic scale

### LINKED ISSUE #1483: Incorrect representation when using logarithmic scale
# Bug report

When enabling logarithmic scale for the y-axis the data is not plotted correctly: the values of the logarithmic scale do not match the representation, they seem to be off by about a 10%.

Tried with various types of xaxis, all with the same result (categorey, numerical, datetime). If the logarithmic scale is switched off the representation is correct.

## Codepen

https://codepen.io/llmora/pen/ZEbEVmJ

## Explanation

**- What is the behavior you expect?**

The data points plotted should be aligned with the y-axis scale.

**- What is happening instead?**

The data points are plotted below the y-axis scale value (for instance for a value of 10 it is plotted at around the value of 9, a value of 100 is plotted around the value of 90, etc.)

**- What error message are you getting?**

No error message displayed or in the console. Tried going back all the way to v2.0.0

### PR DESCRIPTION
**Pull request by llmora**
# New Pull Request

When y-axis ticks are generated for logarithmic scales it does not take into account that ticks must be on power of 10 and above the max-y value. This results in data is not plotted correctly: the values of the logarithmic scale do not match the representation.

Fixes #1483

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by junedchhipa** [comment]
What if the user needs to have a `min` value in log scale?

File: src/modules/Scales.js [hunk 1]
```diff
@@ -152,45 +152,15 @@ export default class Range {
     }
   }
 
-  logarithmicScale(index, yMin, yMax, ticks) {
-    if (yMin < 0 || yMin === Number.MIN_VALUE) yMin = 0.01
+  logarithmicScale(yMax) {
+    let logs = []
```
Comment (PhilippMeissner) [inline src/modules/Scales.js:156]:
```suggestion
    const logs = []
```

File: src/modules/Scales.js [hunk 2]
```diff
@@ -152,45 +152,15 @@ export default class Range {
...
 
-    const base = 10
+    let ticks = Math.ceil(Math.log10(yMax)) + 1; // Get powers of 10 up to our max, and then one more
```
Comment (PhilippMeissner) [inline src/modules/Scales.js:158]:
```suggestion
    const ticks = Math.ceil(Math.log10(yMax)) + 1; // Get powers of 10 up to our max, and then one more
```
